---
name: 'test'

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

concurrency:
  group: test-${{ github.ref || github.head_ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          make kind-e2e-tests
  controller-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          make controller-tests
